import { useCallback, useEffect, useState } from 'react'
import bcrypt from 'bcryptjs'
import { supabase } from '@/lib/supabase'
import type { Department, Employee, EmployeeRole } from '@/types/database'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'
import { Select } from '@/components/ui/Select'
import { Badge } from '@/components/ui/Badge'
import { Dialog } from '@/components/ui/Dialog'
import { PageSpinner } from '@/components/ui/Spinner'
import { useToast } from '@/components/ui/Toast'
import { AvatarPicker, resolveAvatarSrc } from '@/components/ui/AvatarPicker'
import { ROLE_LABELS } from '@/lib/constants'
import { useAuth } from '@/hooks/useAuth'
import { generateEmail, generateEmailPrefix, generateAlternativeEmails, DOMAIN } from '@/lib/email-generator'
import {
  Plus,
  Pencil,
  Building2,
  Users,
  UserPlus,
  UserX,
  UserCheck,
  Trash2,
  KeyRound,
} from 'lucide-react'

/** 자기평가 대상이 될 수 있는 역할 */
const SELF_EVAL_ELIGIBLE_ROLES: string[] = ['employee', 'leader']

const ROLE_OPTIONS: { value: string; label: string }[] = [
  { value: 'employee', label: '직원' },
  { value: 'leader', label: '리더' },
  { value: 'director', label: '이사' },
  { value: 'division_head', label: '본부장' },
  { value: 'ceo', label: '대표이사' },
  { value: 'admin', label: '관리자' },
]

const EMPLOYMENT_TYPE_OPTIONS = [
  { value: 'full_time', label: '정규직' },
  { value: 'contract', label: '계약직' },
  { value: 'intern', label: '인턴' },
  { value: 'part_time', label: '파트타임' },
  { value: 'probation', label: '수습' },
]

const MBTI_OPTIONS = [
  '','ISTJ','ISFJ','INFJ','INTJ','ISTP','ISFP','INFP','INTP',
  'ESTP','ESFP','ENFP','ENTP','ESTJ','ESFJ','ENFJ','ENTJ',
].map(v => ({ value: v, label: v || '선택 안 함' }))

const BLOOD_TYPE_OPTIONS = [
  { value: '', label: '선택 안 함' },
  { value: 'A', label: 'A형' },
  { value: 'B', label: 'B형' },
  { value: 'O', label: 'O형' },
  { value: 'AB', label: 'AB형' },
]

export default function TabEmployees() {
  const { toast } = useToast()
  const { profile } = useAuth()
  const canViewSalary = profile?.role && ['ceo', 'director', 'division_head', 'admin'].includes(profile.role)
  const [departments, setDepartments] = useState<Department[]>([])
  const [employees, setEmployees] = useState<(Employee & { department?: Department })[]>([])
  const [loading, setLoading] = useState(true)

  // 부서 다이얼로그
  const [showDeptDialog, setShowDeptDialog] = useState(false)
  const [editingDept, setEditingDept] = useState<Department | null>(null)
  const [deptName, setDeptName] = useState('')
  const [deptParentId, setDeptParentId] = useState('')

  // 직원 추가 다이얼로그
  const [showInviteDialog, setShowInviteDialog] = useState(false)
  const [inviteForm, setInviteForm] = useState({
    email: '',
    name: '',
    department_id: '',
    role: 'employee' as EmployeeRole,
    password: '',
    birth_date: '',
    address: '',
    phone: '',
    avatar_url: '',
    employee_number: '',
    hire_date: '',
    position: '',
    employment_type: 'full_time',
    emergency_contact: '',
    mbti: '',
    blood_type: '',
    hanja_name: '',
  })
  const [inviting, setInviting] = useState(false)
  const [emailSuggestions, setEmailSuggestions] = useState<string[]>([])
  const [emailAutoGenerated, setEmailAutoGenerated] = useState(false)

  // 직원 수정 다이얼로그
  const [showEditDialog, setShowEditDialog] = useState(false)
  const [editingEmployee, setEditingEmployee] = useState<Employee | null>(null)
  const [editForm, setEditForm] = useState({
    department_id: '',
    role: '',
    birth_date: '',
    address: '',
    phone: '',
    avatar_url: '',
    employee_number: '',
    hire_date: '',
    position: '',
    employment_type: '',
    emergency_contact: '',
    mbti: '',
    blood_type: '',
    hanja_name: '',
  })

  // 비밀번호 변경
  const [showPasswordDialog, setShowPasswordDialog] = useState(false)
  const [passwordTarget, setPasswordTarget] = useState<Employee | null>(null)
  const [newPassword, setNewPassword] = useState('')
  const [resettingPassword, setResettingPassword] = useState(false)

  // 필터
  const [filterDept, setFilterDept] = useState<string>('all')

  // 자기평가 토글 관련
  const [activePeriodId, setActivePeriodId] = useState<string | null>(null)
  const [evalTargets, setEvalTargets] = useState<Record<string, { id: string; status: string }>>({})
  const [togglingEval, setTogglingEval] = useState<Set<string>>(new Set())

  const fetchData = useCallback(async () => {
    const [deptRes, empRes, periodRes] = await Promise.all([
      supabase.from('departments').select('*').order('name'),
      supabase.from('employees').select('*, department:departments(*)').order('name'),
      supabase.from('evaluation_periods').select('*').eq('status', 'in_progress').limit(1).single(),
    ])
    setDepartments(deptRes.data ?? [])
    setEmployees(empRes.data ?? [])

    if (periodRes.data) {
      setActivePeriodId(periodRes.data.id)
      const { data: targets } = await supabase
        .from('evaluation_targets')
        .select('id, employee_id, status')
        .eq('period_id', periodRes.data.id)
      const targetMap: Record<string, { id: string; status: string }> = {}
      targets?.forEach((t: any) => {
        targetMap[t.employee_id] = { id: t.id, status: t.status }
      })
      setEvalTargets(targetMap)
    }

    setLoading(false)
  }, [])

  useEffect(() => {
    fetchData()
  }, [fetchData])

  // ─── 이름 변경 시 이메일 자동 생성 ─────────────────────────────
  async function handleNameChange(name: string) {
    setInviteForm((f) => ({ ...f, name }))

    const email = generateEmail(name)
    if (!email) {
      setEmailSuggestions([])
      if (emailAutoGenerated) setInviteForm((f) => ({ ...f, email: '' }))
      return
    }

    // 자동생성된 이메일이면 자동 갱신
    setInviteForm((f) => ({ ...f, name, email }))
    setEmailAutoGenerated(true)

    // 중복 체크
    const prefix = generateEmailPrefix(name)
    const { data: existing } = await supabase
      .from('employees')
      .select('email')
      .ilike('email', `${prefix}%@${DOMAIN}`)

    if (existing && existing.length > 0) {
      const alts = generateAlternativeEmails(name, existing.length)
      setEmailSuggestions(alts)
      // 기본 이메일이 이미 존재하면 첫 번째 대안으로 설정
      if (existing.some((e) => e.email === email)) {
        setInviteForm((f) => ({ ...f, email: alts[0] || email }))
      }
    } else {
      setEmailSuggestions([])
    }
  }

  function handleEmailManualChange(email: string) {
    setInviteForm((f) => ({ ...f, email }))
    setEmailAutoGenerated(false)
  }

  // ─── 부서 관리 ────────────────────────────────────────────────

  function openCreateDept() {
    setEditingDept(null)
    setDeptName('')
    setDeptParentId('')
    setShowDeptDialog(true)
  }

  function openAddTeam(parentDept: Department) {
    setEditingDept(null)
    setDeptName('')
    setDeptParentId(parentDept.id)
    setShowDeptDialog(true)
  }

  function openEditDept(dept: Department) {
    setEditingDept(dept)
    setDeptName(dept.name)
    setDeptParentId(dept.parent_id || '')
    setShowDeptDialog(true)
  }

  async function handleSaveDept() {
    if (!deptName.trim()) {
      toast('부서명을 입력해주세요', 'error')
      return
    }

    const deptData = {
      name: deptName,
      parent_id: deptParentId || null,
    }

    if (editingDept) {
      const { error } = await supabase
        .from('departments')
        .update(deptData)
        .eq('id', editingDept.id)
      if (error) {
        toast('수정 실패: ' + error.message, 'error')
      } else {
        toast('부서가 수정되었습니다')
        setShowDeptDialog(false)
        fetchData()
      }
    } else {
      const { error } = await supabase.from('departments').insert(deptData)
      if (error) {
        toast('생성 실패: ' + error.message, 'error')
      } else {
        toast('부서가 생성되었습니다')
        setShowDeptDialog(false)
        fetchData()
      }
    }
  }

  async function handleDeleteDept(dept: Department) {
    const deptEmployees = employees.filter((e) => e.department_id === dept.id)
    if (deptEmployees.length > 0) {
      toast('직원이 있는 부서는 삭제할 수 없습니다', 'error')
      return
    }
    if (!confirm(`"${dept.name}" 부서를 삭제하시겠습니까?`)) return

    const { error } = await supabase.from('departments').delete().eq('id', dept.id)
    if (error) {
      toast('삭제 실패: ' + error.message, 'error')
    } else {
      toast('부서가 삭제되었습니다')
      fetchData()
    }
  }

  // ─── 직원 초대 ────────────────────────────────────────────────

  function openInvite() {
    setInviteForm({
      email: '',
      name: '',
      department_id: departments[0]?.id ?? '',
      role: 'employee',
      password: generateTempPassword(),
      birth_date: '',
      address: '',
      phone: '',
      avatar_url: '',
      employee_number: '',
      hire_date: new Date().toISOString().slice(0, 10),
      position: '',
      employment_type: 'full_time',
      emergency_contact: '',
      mbti: '',
      blood_type: '',
      hanja_name: '',
    })
    setEmailSuggestions([])
    setEmailAutoGenerated(false)
    setShowInviteDialog(true)
  }

  function generateTempPassword() {
    return 'Temp' + Math.random().toString(36).slice(2, 8) + '!'
  }

  async function handleInvite() {
    if (!inviteForm.email || !inviteForm.name) {
      toast('이메일과 이름을 입력해주세요', 'error')
      return
    }
    setInviting(true)

    // Step 1: RPC 호출 (비밀번호는 DB에서 bcrypt 해싱)
    const { data, error } = await supabase.rpc('create_employee_with_auth', {
      p_email: inviteForm.email,
      p_password: inviteForm.password,
      p_name: inviteForm.name,
      p_role: inviteForm.role,
      p_department_id: inviteForm.department_id || null,
    })

    if (error) {
      toast('직원 등록 실패: ' + error.message, 'error')
    } else {
      // Step 2: 추가 필드 업데이트
      const employeeId = data as string
      const extraFields: Record<string, string | null> = {}
      if (inviteForm.birth_date) extraFields.birth_date = inviteForm.birth_date
      if (inviteForm.address) extraFields.address = inviteForm.address
      if (inviteForm.phone) extraFields.phone = inviteForm.phone
      if (inviteForm.avatar_url) extraFields.avatar_url = inviteForm.avatar_url
      // employee_number는 hire_date 설정 시 DB 트리거로 자동 생성
      if (inviteForm.hire_date) extraFields.hire_date = inviteForm.hire_date
      if (inviteForm.position) extraFields.position = inviteForm.position
      if (inviteForm.employment_type) extraFields.employment_type = inviteForm.employment_type
      if (inviteForm.emergency_contact) extraFields.emergency_contact = inviteForm.emergency_contact

      if (Object.keys(extraFields).length > 0 && employeeId) {
        await supabase.from('employees').update(extraFields).eq('id', employeeId)
      }

      // Step 3: employee_profiles에 MBTI/혈액형/한자이름 저장
      if (employeeId && (inviteForm.mbti || inviteForm.blood_type || inviteForm.hanja_name)) {
        const { error: profileErr } = await supabase.from('employee_profiles').upsert({
          employee_id: employeeId,
          mbti: inviteForm.mbti || null,
          blood_type: inviteForm.blood_type || null,
          hanja_name: inviteForm.hanja_name || null,
          birth_date: inviteForm.birth_date || null,
        }, { onConflict: 'employee_id' })
        if (profileErr) {
          toast('MBTI/혈액형 저장 실패: ' + profileErr.message, 'error')
        }
      }

      // Step 4: 연봉 저장 (employee_hr_details)
      if (employeeId && (inviteForm as any).annual_salary) {
        await supabase.from('employee_hr_details').upsert({
          employee_id: employeeId,
          annual_salary: (inviteForm as any).annual_salary,
        }, { onConflict: 'employee_id' })
      }

      toast(`${inviteForm.name}님이 등록되었습니다. 임시 비밀번호: ${inviteForm.password}`, 'info')
      setShowInviteDialog(false)
      fetchData()
    }
    setInviting(false)
  }

  // ─── 직원 수정 ────────────────────────────────────────────────

  async function openEditEmployee(emp: Employee) {
    setEditingEmployee(emp)

    // employee_profiles에서 MBTI/혈액형/한자이름 로드
    let mbti = '', blood_type = '', hanja_name = ''
    const { data: profile } = await supabase
      .from('employee_profiles')
      .select('mbti, blood_type, hanja_name')
      .eq('employee_id', emp.id)
      .limit(1)
      .single()
    if (profile) {
      mbti = profile.mbti ?? ''
      blood_type = profile.blood_type ?? ''
      hanja_name = profile.hanja_name ?? ''
    }

    setEditForm({
      department_id: emp.department_id ?? '',
      role: emp.role,
      birth_date: emp.birth_date ?? '',
      address: emp.address ?? '',
      phone: emp.phone ?? '',
      avatar_url: emp.avatar_url ?? '',
      employee_number: emp.employee_number ?? '',
      hire_date: emp.hire_date ?? '',
      position: emp.position ?? '',
      employment_type: emp.employment_type ?? '',
      emergency_contact: emp.emergency_contact ?? '',
      mbti,
      blood_type,
      hanja_name,
    })
    setShowEditDialog(true)
  }

  async function handleEditEmployee() {
    if (!editingEmployee) return

    const { error } = await supabase
      .from('employees')
      .update({
        department_id: editForm.department_id || null,
        role: editForm.role,
        birth_date: editForm.birth_date || null,
        address: editForm.address || null,
        phone: editForm.phone || null,
        avatar_url: editForm.avatar_url || null,
        hire_date: editForm.hire_date || null,
        position: editForm.position || null,
        employment_type: editForm.employment_type || null,
        emergency_contact: editForm.emergency_contact || null,
      })
      .eq('id', editingEmployee.id)

    if (error) {
      toast('수정 실패: ' + error.message, 'error')
      return
    }

    // employee_profiles 업데이트
    if (editForm.mbti || editForm.blood_type || editForm.hanja_name) {
      const { error: profileErr } = await supabase.from('employee_profiles').upsert({
        employee_id: editingEmployee.id,
        mbti: editForm.mbti || null,
        blood_type: editForm.blood_type || null,
        hanja_name: editForm.hanja_name || null,
        birth_date: editForm.birth_date || null,
      }, { onConflict: 'employee_id' })
      if (profileErr) {
        toast('MBTI/혈액형 저장 실패: ' + profileErr.message, 'error')
      }
    }

    toast('직원 정보가 수정되었습니다')
    setShowEditDialog(false)
    fetchData()
  }

  async function handleToggleActive(emp: Employee) {
    const action = emp.is_active ? '비활성화' : '활성화'
    if (!confirm(`${emp.name}님을 ${action}하시겠습니까?`)) return

    const { error } = await supabase
      .from('employees')
      .update({ is_active: !emp.is_active })
      .eq('id', emp.id)

    if (error) {
      toast('변경 실패: ' + error.message, 'error')
    } else {
      toast(`${emp.name}님이 ${action}되었습니다`)
      fetchData()
    }
  }

  async function handleDeleteEmployee(emp: Employee) {
    const msg = emp.is_active
      ? `${emp.name}님을 퇴사 처리하시겠습니까?\n비활성화되며, 퇴사 후 관리가 가능합니다.`
      : `${emp.name}님을 완전히 삭제하시겠습니까?\n이 작업은 되돌릴 수 없습니다.`

    if (!confirm(msg)) return

    if (emp.is_active) {
      // 퇴사 처리 (비활성화)
      const { error } = await supabase.from('employees').update({
        is_active: false,
      }).eq('id', emp.id)

      if (error) {
        toast('퇴사 처리 실패: ' + error.message, 'error')
      } else {
        toast(`${emp.name}님이 퇴사 처리되었습니다`)
        fetchData()
      }
    } else {
      // 이미 비활성인 경우 완전 삭제 시도
      // 관련 테이블 FK 참조 먼저 정리
      try {
        await supabase.from('approval_steps').delete().eq('approver_id', emp.id)
        await supabase.from('probation_evaluations').delete().eq('employee_id', emp.id)
        await supabase.from('probation_evaluations').delete().eq('evaluator_id', emp.id)
        await supabase.from('employee_hr_details').delete().eq('employee_id', emp.id)
        await supabase.from('employee_profiles').delete().eq('employee_id', emp.id)
        await supabase.from('mentor_assignments').delete().eq('mentor_id', emp.id)
        await supabase.from('mentor_assignments').delete().eq('mentee_id', emp.id)
        await supabase.from('peer_reviews').delete().eq('reviewer_id', emp.id)
        await supabase.from('peer_reviews').delete().eq('target_id', emp.id)
      } catch {
        // 테이블이 없을 수 있으므로 무시
      }

      const { error } = await supabase.rpc('delete_employee', {
        p_employee_id: emp.id,
      })

      if (error) {
        // RPC 실패 시 직접 삭제 시도
        const { error: directErr } = await supabase.from('employees').delete().eq('id', emp.id)
        if (directErr) {
          toast('삭제 실패: 이 직원과 연결된 데이터가 있어 삭제할 수 없습니다. 비활성 상태로 유지됩니다.', 'error')
        } else {
          toast(`${emp.name}님이 삭제되었습니다`)
          fetchData()
        }
      } else {
        toast(`${emp.name}님이 삭제되었습니다`)
        fetchData()
      }
    }
  }

  function openPasswordReset(emp: Employee) {
    setPasswordTarget(emp)
    setNewPassword(generateTempPassword())
    setShowPasswordDialog(true)
  }

  async function handleResetPassword() {
    if (!passwordTarget) return
    if (newPassword.length < 6) {
      toast('비밀번호는 6자 이상이어야 합니다', 'error')
      return
    }

    setResettingPassword(true)
    const hashedPassword = await bcrypt.hash(newPassword, 10)
    const { error } = await supabase.rpc('reset_employee_password', {
      p_employee_id: passwordTarget.id,
      p_new_password: hashedPassword,
    })

    if (error) {
      toast('비밀번호 변경 실패: ' + error.message, 'error')
    } else {
      toast(`${passwordTarget.name}님의 비밀번호가 변경되었습니다. 새 비밀번호: ${newPassword}`, 'info')
      setShowPasswordDialog(false)
    }
    setResettingPassword(false)
  }

  async function handleToggleSelfEval(emp: Employee) {
    if (!activePeriodId) {
      toast('진행 중인 평가 기간이 없습니다', 'error')
      return
    }
    if (!SELF_EVAL_ELIGIBLE_ROLES.includes(emp.role)) {
      toast('해당 역할은 자기평가 대상이 아닙니다', 'error')
      return
    }

    setTogglingEval((prev) => new Set(prev).add(emp.id))

    const existing = evalTargets[emp.id]
    if (existing) {
      if (existing.status !== 'pending') {
        toast('이미 진행된 평가는 비활성화할 수 없습니다', 'error')
        setTogglingEval((prev) => { const s = new Set(prev); s.delete(emp.id); return s })
        return
      }
      await supabase.from('self_evaluations').delete().eq('target_id', existing.id)
      const { error } = await supabase.from('evaluation_targets').delete().eq('id', existing.id)
      if (error) {
        toast('자기평가 비활성화 실패: ' + error.message, 'error')
      } else {
        toast(`${emp.name}님의 자기평가가 비활성화되었습니다`)
        setEvalTargets((prev) => { const next = { ...prev }; delete next[emp.id]; return next })
      }
    } else {
      const { data: newTarget, error } = await supabase
        .from('evaluation_targets')
        .insert({ period_id: activePeriodId, employee_id: emp.id, status: 'pending' })
        .select('id')
        .single()

      if (error) {
        toast('자기평가 활성화 실패: ' + error.message, 'error')
      } else if (newTarget) {
        const { data: activeItems } = await supabase
          .from('evaluation_items')
          .select('id')
          .eq('is_active', true)
        if (activeItems && activeItems.length > 0) {
          await supabase.from('self_evaluations').insert(
            activeItems.map((item: any) => ({ target_id: newTarget.id, item_id: item.id }))
          )
        }
        toast(`${emp.name}님의 자기평가가 활성화되었습니다`)
        setEvalTargets((prev) => ({ ...prev, [emp.id]: { id: newTarget.id, status: 'pending' } }))
      }
    }

    setTogglingEval((prev) => { const s = new Set(prev); s.delete(emp.id); return s })
  }

  if (loading) return <PageSpinner />

  const activeEmployees = employees.filter((e) => e.is_active)
  const inactiveEmployees = employees.filter((e) => !e.is_active)

  const filteredEmployees =
    filterDept === 'all'
      ? activeEmployees
      : filterDept === 'none'
      ? activeEmployees.filter((e) => !e.department_id)
      : activeEmployees.filter((e) => e.department_id === filterDept)

  return (
    <div className="space-y-6">
      <p className="text-sm text-gray-500">부서 및 직원 정보를 관리합니다.</p>

      {/* ─── 부서 관리 ──────────────────────────────────────── */}
      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <div className="flex items-center gap-2">
            <Building2 className="h-5 w-5 text-gray-400" />
            <CardTitle>부서 관리</CardTitle>
          </div>
          <Button size="sm" onClick={openCreateDept}>
            <Plus className="h-3 w-3 mr-1" />
            부서 추가
          </Button>
        </CardHeader>
        <CardContent>
          {departments.length === 0 ? (
            <p className="text-sm text-gray-400 text-center py-4">등록된 부서가 없습니다</p>
          ) : (
            <div className="space-y-2">
              {/* 상위 부서 (parent_id 없는 것) */}
              {departments.filter((d) => !d.parent_id).map((dept) => {
                const count = employees.filter((e) => e.department_id === dept.id).length
                const childDepts = departments.filter((d) => d.parent_id === dept.id)
                return (
                  <div key={dept.id}>
                    <div className="flex items-center justify-between rounded-lg border-2 border-brand-200 bg-brand-50/30 px-4 py-3">
                      <div>
                        <p className="text-sm font-bold text-gray-900">{dept.name}</p>
                        <p className="text-xs text-gray-500">{count}명 · 부서{childDepts.length > 0 ? ` · 하위 팀 ${childDepts.length}개` : ''}</p>
                      </div>
                      <div className="flex items-center gap-2">
                        <button
                          onClick={() => openAddTeam(dept)}
                          className="flex items-center gap-1 rounded-md px-2 py-1 text-xs font-medium text-brand-600 bg-brand-100 hover:bg-brand-200 transition-colors"
                        >
                          <Plus className="h-3 w-3" /> 팀 추가
                        </button>
                        <button onClick={() => openEditDept(dept)} className="rounded p-1 text-gray-400 hover:bg-gray-100 hover:text-gray-600">
                          <Pencil className="h-3.5 w-3.5" />
                        </button>
                        <button onClick={() => handleDeleteDept(dept)} className="rounded p-1 text-gray-400 hover:bg-red-50 hover:text-red-600">
                          <Trash2 className="h-3.5 w-3.5" />
                        </button>
                      </div>
                    </div>
                    {/* 하위 팀 */}
                    {childDepts.map((child) => {
                      const childCount = employees.filter((e) => e.department_id === child.id).length
                      return (
                        <div key={child.id} className="flex items-center justify-between rounded-lg border border-gray-200 bg-gray-50/50 px-4 py-2.5 ml-6 mt-1">
                          <div className="flex items-center gap-2">
                            <span className="text-gray-300">└</span>
                            <div>
                              <p className="text-sm font-medium text-gray-800">{child.name}</p>
                              <p className="text-xs text-gray-500">{childCount}명 · 팀</p>
                            </div>
                          </div>
                          <div className="flex gap-1">
                            <button onClick={() => openEditDept(child)} className="rounded p-1 text-gray-400 hover:bg-gray-100 hover:text-gray-600">
                              <Pencil className="h-3.5 w-3.5" />
                            </button>
                            <button onClick={() => handleDeleteDept(child)} className="rounded p-1 text-gray-400 hover:bg-red-50 hover:text-red-600">
                              <Trash2 className="h-3.5 w-3.5" />
                            </button>
                          </div>
                        </div>
                      )
                    })}
                  </div>
                )
              })}
              {/* parent_id가 있는데 부모가 삭제된 고아 부서 */}
              {departments.filter((d) => d.parent_id && !departments.find((p) => p.id === d.parent_id)).map((dept) => {
                const count = employees.filter((e) => e.department_id === dept.id).length
                return (
                  <div key={dept.id} className="flex items-center justify-between rounded-lg border border-gray-200 px-4 py-3">
                    <div>
                      <p className="text-sm font-medium text-gray-900">{dept.name}</p>
                      <p className="text-xs text-gray-500">{count}명</p>
                    </div>
                    <div className="flex gap-1">
                      <button onClick={() => openEditDept(dept)} className="rounded p-1 text-gray-400 hover:bg-gray-100 hover:text-gray-600">
                        <Pencil className="h-3.5 w-3.5" />
                      </button>
                      <button onClick={() => handleDeleteDept(dept)} className="rounded p-1 text-gray-400 hover:bg-red-50 hover:text-red-600">
                        <Trash2 className="h-3.5 w-3.5" />
                      </button>
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </CardContent>
      </Card>

      {/* ─── 직원 관리 ──────────────────────────────────────── */}
      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <div className="flex items-center gap-2">
            <Users className="h-5 w-5 text-gray-400" />
            <CardTitle>직원 관리</CardTitle>
            <Badge variant="default">{activeEmployees.length}명</Badge>
          </div>
          <div className="flex items-center gap-3">
            <Select
              options={[
                { value: 'all', label: '전체' },
                ...departments.map((d) => ({ value: d.id, label: d.name })),
                { value: 'none', label: '부서 미지정' },
              ]}
              value={filterDept}
              onChange={(e) => setFilterDept(e.target.value)}
              className="w-40"
            />
            <Button size="sm" onClick={openInvite}>
              <UserPlus className="h-3 w-3 mr-1" />
              직원 추가
            </Button>
          </div>
        </CardHeader>
        <CardContent className="p-0">
          {filteredEmployees.length === 0 ? (
            <div className="flex h-20 items-center justify-center text-sm text-gray-400">
              직원이 없습니다
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm min-w-[800px]">
                <thead>
                  <tr className="border-b border-gray-100 bg-gray-50">
                    <th className="px-6 py-3 text-left font-medium text-gray-500">사원번호</th>
                    <th className="px-6 py-3 text-left font-medium text-gray-500">이름</th>
                    <th className="px-6 py-3 text-left font-medium text-gray-500">부서</th>
                    <th className="px-6 py-3 text-left font-medium text-gray-500">팀</th>
                    <th className="px-6 py-3 text-left font-medium text-gray-500">직무</th>
                    <th className="px-6 py-3 text-left font-medium text-gray-500">역할</th>
                    <th className="px-6 py-3 text-left font-medium text-gray-500">상태</th>
                    {activePeriodId && (
                      <th className="px-6 py-3 text-center font-medium text-gray-500">자기평가</th>
                    )}
                    <th className="px-6 py-3 text-left font-medium text-gray-500">작업</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredEmployees.map((emp) => {
                    const avatarSrc = resolveAvatarSrc(emp.avatar_url)
                    return (
                      <tr
                        key={emp.id}
                        className={`border-b border-gray-50 ${
                          emp.is_active ? 'hover:bg-gray-50' : 'bg-gray-50 opacity-60'
                        }`}
                      >
                        <td className="px-6 py-3 text-gray-500 text-xs font-mono">
                          {emp.employee_number || '-'}
                        </td>
                        <td className="px-6 py-3 font-medium text-gray-900">
                          <div className="flex items-center gap-2">
                            {avatarSrc ? (
                              <img src={avatarSrc} alt="" className="h-7 w-7 rounded-full" />
                            ) : (
                              <div className="h-7 w-7 rounded-full bg-gray-200 flex items-center justify-center text-xs text-gray-500">
                                {emp.name.charAt(0)}
                              </div>
                            )}
                            {emp.name}
                          </div>
                        </td>
                        <td className="px-6 py-3 text-gray-600">
                          {(() => {
                            const dept = (emp as any).department
                            if (!dept) return '-'
                            // 팀이면 부모 부서 이름 표시
                            if (dept.parent_id) {
                              const parent = departments.find((d) => d.id === dept.parent_id)
                              return parent?.name || '-'
                            }
                            return dept.name
                          })()}
                        </td>
                        <td className="px-6 py-3 text-gray-600">
                          {(() => {
                            const dept = (emp as any).department
                            if (!dept) return '-'
                            // 팀이면 팀 이름, 부서면 '-'
                            return dept.parent_id ? dept.name : '-'
                          })()}
                        </td>
                        <td className="px-6 py-3 text-gray-600 text-xs">
                          {emp.position || '-'}
                        </td>
                        <td className="px-6 py-3">
                          <Badge variant="primary">
                            {ROLE_LABELS[emp.role as EmployeeRole] ?? emp.role}
                          </Badge>
                        </td>
                        <td className="px-6 py-3">
                          <Badge variant={emp.is_active ? 'success' : 'danger'}>
                            {emp.is_active ? '활성' : '비활성'}
                          </Badge>
                        </td>
                        {activePeriodId && (
                          <td className="px-6 py-3 text-center">
                            {SELF_EVAL_ELIGIBLE_ROLES.includes(emp.role) ? (
                              <button
                                onClick={() => handleToggleSelfEval(emp)}
                                disabled={togglingEval.has(emp.id) || (evalTargets[emp.id]?.status != null && evalTargets[emp.id]?.status !== 'pending')}
                                className="relative inline-flex h-6 w-11 items-center rounded-full transition-colors focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2 disabled:opacity-50"
                                style={{
                                  backgroundColor: evalTargets[emp.id] ? '#6d28d9' : '#d1d5db',
                                }}
                                title={
                                  evalTargets[emp.id]
                                    ? evalTargets[emp.id].status !== 'pending'
                                      ? `진행 중 (${evalTargets[emp.id].status})`
                                      : '자기평가 활성 — 클릭하여 비활성화'
                                    : '자기평가 비활성 — 클릭하여 활성화'
                                }
                              >
                                <span
                                  className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                                    evalTargets[emp.id] ? 'translate-x-6' : 'translate-x-1'
                                  }`}
                                />
                              </button>
                            ) : (
                              <span className="text-xs text-gray-400">—</span>
                            )}
                          </td>
                        )}
                        <td className="px-6 py-3">
                          <div className="flex gap-1">
                            <button
                              onClick={() => openEditEmployee(emp)}
                              className="rounded p-1 text-gray-400 hover:bg-gray-100 hover:text-gray-600"
                              title="수정"
                            >
                              <Pencil className="h-4 w-4" />
                            </button>
                            <button
                              onClick={() => openPasswordReset(emp)}
                              className="rounded p-1 text-gray-400 hover:bg-amber-50 hover:text-amber-600"
                              title="비밀번호 변경"
                            >
                              <KeyRound className="h-4 w-4" />
                            </button>
                            <button
                              onClick={() => handleToggleActive(emp)}
                              className="rounded p-1 text-gray-400 hover:bg-gray-100 hover:text-gray-600"
                              title={emp.is_active ? '비활성화' : '활성화'}
                            >
                              {emp.is_active ? (
                                <UserX className="h-4 w-4" />
                              ) : (
                                <UserCheck className="h-4 w-4" />
                              )}
                            </button>
                            <button
                              onClick={() => handleDeleteEmployee(emp)}
                              className="rounded p-1 text-gray-400 hover:bg-red-50 hover:text-red-600"
                              title={emp.is_active ? '퇴사 처리' : '삭제'}
                            >
                              <Trash2 className="h-4 w-4" />
                            </button>
                          </div>
                        </td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>

      {/* ─── 퇴사 관리 ──────────────────────────────────────── */}
      {inactiveEmployees.length > 0 && (
        <Card>
          <CardHeader className="flex flex-row items-center justify-between">
            <div className="flex items-center gap-2">
              <Users className="h-5 w-5 text-red-400" />
              <CardTitle>퇴사 관리</CardTitle>
              <Badge variant="danger">{inactiveEmployees.length}명</Badge>
            </div>
          </CardHeader>
          <CardContent>
            <div className="overflow-x-auto">
              <table className="w-full text-sm min-w-[600px]">
                <thead>
                  <tr className="border-b border-gray-100 bg-gray-50">
                    <th className="px-6 py-3 text-left font-medium text-gray-500">사원번호</th>
                    <th className="px-6 py-3 text-left font-medium text-gray-500">이름</th>
                    <th className="px-6 py-3 text-left font-medium text-gray-500">부서</th>
                    <th className="px-6 py-3 text-left font-medium text-gray-500">직무</th>
                    <th className="px-6 py-3 text-left font-medium text-gray-500">상태</th>
                    <th className="px-6 py-3 text-left font-medium text-gray-500">작업</th>
                  </tr>
                </thead>
                <tbody>
                  {inactiveEmployees.map((emp) => (
                    <tr key={emp.id} className="border-b border-gray-50 bg-red-50/30">
                      <td className="px-6 py-3 text-gray-500 text-xs font-mono">{emp.employee_number || '-'}</td>
                      <td className="px-6 py-3 font-medium text-gray-600">{emp.name}</td>
                      <td className="px-6 py-3 text-gray-500">{(emp as any).department?.name ?? '-'}</td>
                      <td className="px-6 py-3 text-gray-500 text-xs">{emp.position || '-'}</td>
                      <td className="px-6 py-3"><Badge variant="danger">퇴사</Badge></td>
                      <td className="px-6 py-3">
                        <div className="flex gap-2">
                          <button
                            onClick={async () => {
                              if (!confirm(`${emp.name}님을 복직 처리하시겠습니까?`)) return
                              const { error } = await supabase.from('employees').update({ is_active: true }).eq('id', emp.id)
                              if (error) toast('복직 실패: ' + error.message, 'error')
                              else { toast(`${emp.name}님이 복직 처리되었습니다`, 'success'); fetchData() }
                            }}
                            className="text-xs text-blue-600 hover:underline"
                          >
                            복직
                          </button>
                          <button
                            onClick={() => handleDeleteEmployee(emp)}
                            className="text-xs text-red-600 hover:underline"
                          >
                            완전 삭제
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>
      )}

      {/* ─── 부서 추가/수정 다이얼로그 ─────────────────────── */}
      <Dialog
        open={showDeptDialog}
        onClose={() => setShowDeptDialog(false)}
        title={editingDept ? '부서/팀 수정' : deptParentId ? `팀 추가 — ${departments.find((d) => d.id === deptParentId)?.name || ''}` : '부서 추가'}
      >
        <div className="space-y-4">
          <Input
            id="dept-name"
            label={deptParentId && !editingDept ? '팀명' : '부서명'}
            value={deptName}
            onChange={(e) => setDeptName(e.target.value)}
            placeholder={deptParentId && !editingDept ? '예: 마케팅팀' : '예: 브랜드사업본부'}
          />
          <Select
            id="dept-parent"
            label="상위 부서"
            options={[
              { value: '', label: '없음 (최상위 부서)' },
              ...departments
                .filter((d) => d.id !== editingDept?.id && !d.parent_id)
                .map((d) => ({ value: d.id, label: d.name })),
            ]}
            value={deptParentId}
            onChange={(e) => setDeptParentId(e.target.value)}
          />
          <div className="flex justify-end gap-3 pt-2">
            <Button variant="outline" onClick={() => setShowDeptDialog(false)}>
              취소
            </Button>
            <Button onClick={handleSaveDept}>
              {editingDept ? '수정' : '추가'}
            </Button>
          </div>
        </div>
      </Dialog>

      {/* ─── 직원 추가 다이얼로그 ──────────────────────────── */}
      <Dialog
        open={showInviteDialog}
        onClose={() => setShowInviteDialog(false)}
        title="직원 추가"
        className="max-w-xl"
      >
        <div className="space-y-4 max-h-[70vh] overflow-y-auto pr-1">
          <Input
            id="invite-name"
            label="이름"
            value={inviteForm.name}
            onChange={(e) => handleNameChange(e.target.value)}
            placeholder="홍길동"
          />
          <div>
            <Input
              id="invite-email"
              label="이메일"
              type="email"
              value={inviteForm.email}
              onChange={(e) => handleEmailManualChange(e.target.value)}
              placeholder="user@interohrigin.com"
            />
            {emailSuggestions.length > 0 && (
              <div className="mt-1.5 flex flex-wrap gap-1.5">
                <span className="text-xs text-gray-500">추천:</span>
                {emailSuggestions.map((alt) => (
                  <button
                    key={alt}
                    type="button"
                    onClick={() => {
                      setInviteForm((f) => ({ ...f, email: alt }))
                      setEmailAutoGenerated(true)
                    }}
                    className="rounded-full bg-brand-50 px-2 py-0.5 text-xs text-brand-700 hover:bg-brand-100 transition-colors"
                  >
                    {alt}
                  </button>
                ))}
              </div>
            )}
          </div>
          {/* 사원번호 / 입사일 */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <Input
                id="invite-empno"
                label="사원번호"
                value={inviteForm.employee_number}
                onChange={(e) => setInviteForm({ ...inviteForm, employee_number: e.target.value })}
                placeholder="자동 생성 (입사일 기반)"
                disabled
              />
              <p className="text-[10px] text-gray-400 mt-1">입사일 저장 시 자동 생성 (YYMMDDRR)</p>
            </div>
            <Input
              id="invite-hire-date"
              label="입사일 *"
              type="date"
              value={inviteForm.hire_date}
              onChange={(e) => setInviteForm({ ...inviteForm, hire_date: e.target.value })}
            />
          </div>

          <div className="grid grid-cols-3 gap-4">
            <Select
              id="invite-dept"
              label="부서"
              options={[
                { value: '', label: '부서 미지정' },
                ...departments.filter((d) => !d.parent_id).map((d) => ({ value: d.id, label: d.name })),
              ]}
              value={(() => {
                // 현재 선택된 department_id가 팀이면 부모 부서 ID 반환
                const current = departments.find((d) => d.id === inviteForm.department_id)
                if (current?.parent_id) return current.parent_id
                return inviteForm.department_id
              })()}
              onChange={(e) => setInviteForm({ ...inviteForm, department_id: e.target.value })}
            />
            <Select
              id="invite-team"
              label="팀"
              options={[
                { value: '', label: '팀 미지정' },
                ...departments.filter((d) => {
                  const currentDept = departments.find((dd) => dd.id === inviteForm.department_id)
                  const parentId = currentDept?.parent_id || inviteForm.department_id
                  return d.parent_id === parentId
                }).map((d) => ({ value: d.id, label: d.name })),
              ]}
              value={(() => {
                const current = departments.find((d) => d.id === inviteForm.department_id)
                return current?.parent_id ? inviteForm.department_id : ''
              })()}
              onChange={(e) => {
                if (e.target.value) {
                  setInviteForm({ ...inviteForm, department_id: e.target.value })
                } else {
                  // 팀 미지정 → 부서 ID 유지
                  const current = departments.find((d) => d.id === inviteForm.department_id)
                  const parentId = current?.parent_id || inviteForm.department_id
                  setInviteForm({ ...inviteForm, department_id: parentId })
                }
              }}
            />
            <Select
              id="invite-role"
              label="역할"
              options={ROLE_OPTIONS}
              value={inviteForm.role}
              onChange={(e) =>
                setInviteForm({ ...inviteForm, role: e.target.value as EmployeeRole })
              }
            />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <Input
              id="invite-birth"
              label="생년월일"
              type="date"
              value={inviteForm.birth_date}
              onChange={(e) => setInviteForm({ ...inviteForm, birth_date: e.target.value })}
            />
            <Input
              id="invite-phone"
              label="연락처"
              type="tel"
              value={inviteForm.phone}
              onChange={(e) => setInviteForm({ ...inviteForm, phone: e.target.value })}
              placeholder="010-0000-0000"
            />
          </div>
          {/* 직무 / 입사구분 / 연봉 */}
          <div className={`grid ${canViewSalary ? 'grid-cols-3' : 'grid-cols-2'} gap-4`}>
            <Input
              id="invite-position"
              label="직무"
              value={inviteForm.position}
              onChange={(e) => setInviteForm({ ...inviteForm, position: e.target.value })}
              placeholder="마케팅, 개발, 디자인 등"
            />
            <Select
              id="invite-employment-type"
              label="입사구분"
              options={EMPLOYMENT_TYPE_OPTIONS}
              value={inviteForm.employment_type}
              onChange={(e) => setInviteForm({ ...inviteForm, employment_type: e.target.value })}
            />
            {canViewSalary && (
              <Input
                id="invite-salary"
                label="연봉 (만원)"
                type="number"
                value={(inviteForm as any).annual_salary || ''}
                onChange={(e) => setInviteForm({ ...inviteForm, annual_salary: e.target.value ? parseInt(e.target.value) * 10000 : '' } as any)}
                placeholder="3000"
              />
            )}
          </div>

          {/* MBTI / 혈액형 / 한자이름 */}
          <div className="grid grid-cols-3 gap-4">
            <Select
              id="invite-mbti"
              label="MBTI"
              options={MBTI_OPTIONS}
              value={inviteForm.mbti}
              onChange={(e) => setInviteForm({ ...inviteForm, mbti: e.target.value })}
            />
            <Select
              id="invite-blood"
              label="혈액형"
              options={BLOOD_TYPE_OPTIONS}
              value={inviteForm.blood_type}
              onChange={(e) => setInviteForm({ ...inviteForm, blood_type: e.target.value })}
            />
            <Input
              id="invite-hanja"
              label="한자이름"
              value={inviteForm.hanja_name}
              onChange={(e) => setInviteForm({ ...inviteForm, hanja_name: e.target.value })}
              placeholder="洪吉東"
            />
          </div>

          {/* 비상연락처 */}
          <Input
            id="invite-emergency"
            label="비상연락처"
            value={inviteForm.emergency_contact}
            onChange={(e) => setInviteForm({ ...inviteForm, emergency_contact: e.target.value })}
            placeholder="관계: 배우자, 010-0000-0000"
          />

          <Input
            id="invite-address"
            label="주소"
            value={inviteForm.address}
            onChange={(e) => setInviteForm({ ...inviteForm, address: e.target.value })}
            placeholder="서울특별시 강남구..."
          />
          <AvatarPicker
            value={inviteForm.avatar_url}
            onChange={(url) => setInviteForm({ ...inviteForm, avatar_url: url })}
          />
          <div>
            <Input
              id="invite-password"
              label="임시 비밀번호"
              value={inviteForm.password}
              onChange={(e) => setInviteForm({ ...inviteForm, password: e.target.value })}
            />
            <p className="mt-1 text-xs text-gray-500">
              직원에게 이 임시 비밀번호를 전달해주세요. 최초 로그인 후 변경 권장.
            </p>
          </div>
          <div className="flex justify-end gap-3 pt-2">
            <Button variant="outline" onClick={() => setShowInviteDialog(false)}>
              취소
            </Button>
            <Button onClick={handleInvite} disabled={inviting}>
              {inviting ? '등록 중...' : '등록'}
            </Button>
          </div>
        </div>
      </Dialog>

      {/* ─── 직원 수정 다이얼로그 ──────────────────────────── */}
      <Dialog
        open={showEditDialog}
        onClose={() => setShowEditDialog(false)}
        title={`직원 수정 — ${editingEmployee?.name}`}
        className="max-w-xl"
      >
        <div className="space-y-4 max-h-[70vh] overflow-y-auto pr-1">
          {/* 사원번호 / 입사일 */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <Input
                id="edit-empno"
                label="사원번호"
                value={editForm.employee_number}
                onChange={(e) => setEditForm({ ...editForm, employee_number: e.target.value })}
                placeholder="자동 생성"
                disabled
              />
              <p className="text-[10px] text-gray-400 mt-1">입사일 기반 자동 생성 (YYMMDDRR)</p>
            </div>
            <Input
              id="edit-hire-date"
              label="입사일"
              type="date"
              value={editForm.hire_date}
              onChange={(e) => setEditForm({ ...editForm, hire_date: e.target.value })}
            />
          </div>

          <div className="grid grid-cols-3 gap-4">
            <Select
              id="edit-dept"
              label="부서"
              options={[
                { value: '', label: '부서 미지정' },
                ...departments.filter((d) => !d.parent_id).map((d) => ({ value: d.id, label: d.name })),
              ]}
              value={(() => {
                const current = departments.find((d) => d.id === editForm.department_id)
                if (current?.parent_id) return current.parent_id
                return editForm.department_id
              })()}
              onChange={(e) => setEditForm({ ...editForm, department_id: e.target.value })}
            />
            <Select
              id="edit-team"
              label="팀"
              options={[
                { value: '', label: '팀 미지정' },
                ...departments.filter((d) => {
                  const currentDept = departments.find((dd) => dd.id === editForm.department_id)
                  const parentId = currentDept?.parent_id || editForm.department_id
                  return d.parent_id === parentId
                }).map((d) => ({ value: d.id, label: d.name })),
              ]}
              value={(() => {
                const current = departments.find((d) => d.id === editForm.department_id)
                return current?.parent_id ? editForm.department_id : ''
              })()}
              onChange={(e) => {
                if (e.target.value) {
                  setEditForm({ ...editForm, department_id: e.target.value })
                } else {
                  const current = departments.find((d) => d.id === editForm.department_id)
                  const parentId = current?.parent_id || editForm.department_id
                  setEditForm({ ...editForm, department_id: parentId })
                }
              }}
            />
            <Select
              id="edit-role"
              label="역할"
              options={ROLE_OPTIONS}
              value={editForm.role}
              onChange={(e) => setEditForm({ ...editForm, role: e.target.value })}
            />
          </div>

          {/* 직무 / 입사구분 / 연봉 */}
          <div className={`grid ${canViewSalary ? 'grid-cols-3' : 'grid-cols-2'} gap-4`}>
            <Input
              id="edit-position"
              label="직무"
              value={editForm.position}
              onChange={(e) => setEditForm({ ...editForm, position: e.target.value })}
              placeholder="마케팅, 개발, 디자인 등"
            />
            <Select
              id="edit-employment-type"
              label="입사구분"
              options={[{ value: '', label: '선택 안 함' }, ...EMPLOYMENT_TYPE_OPTIONS]}
              value={editForm.employment_type}
              onChange={(e) => setEditForm({ ...editForm, employment_type: e.target.value })}
            />
            {canViewSalary && (
              <Input
                id="edit-salary"
                label="연봉 (만원)"
                type="number"
                value={(editForm as any).annual_salary || ''}
                onChange={(e) => setEditForm({ ...editForm, annual_salary: e.target.value ? parseInt(e.target.value) * 10000 : '' } as any)}
                placeholder="3000"
              />
            )}
          </div>

          <div className="grid grid-cols-2 gap-4">
            <Input
              id="edit-birth"
              label="생년월일"
              type="date"
              value={editForm.birth_date}
              onChange={(e) => setEditForm({ ...editForm, birth_date: e.target.value })}
            />
            <Input
              id="edit-phone"
              label="연락처"
              type="tel"
              value={editForm.phone}
              onChange={(e) => setEditForm({ ...editForm, phone: e.target.value })}
              placeholder="010-0000-0000"
            />
          </div>

          {/* MBTI / 혈액형 / 한자이름 */}
          <div className="grid grid-cols-3 gap-4">
            <Select
              id="edit-mbti"
              label="MBTI"
              options={MBTI_OPTIONS}
              value={editForm.mbti}
              onChange={(e) => setEditForm({ ...editForm, mbti: e.target.value })}
            />
            <Select
              id="edit-blood"
              label="혈액형"
              options={BLOOD_TYPE_OPTIONS}
              value={editForm.blood_type}
              onChange={(e) => setEditForm({ ...editForm, blood_type: e.target.value })}
            />
            <Input
              id="edit-hanja"
              label="한자이름"
              value={editForm.hanja_name}
              onChange={(e) => setEditForm({ ...editForm, hanja_name: e.target.value })}
              placeholder="洪吉東"
            />
          </div>

          {/* 비상연락처 */}
          <Input
            id="edit-emergency"
            label="비상연락처"
            value={editForm.emergency_contact}
            onChange={(e) => setEditForm({ ...editForm, emergency_contact: e.target.value })}
            placeholder="관계: 배우자, 010-0000-0000"
          />

          <Input
            id="edit-address"
            label="주소"
            value={editForm.address}
            onChange={(e) => setEditForm({ ...editForm, address: e.target.value })}
            placeholder="서울특별시 강남구..."
          />
          <AvatarPicker
            value={editForm.avatar_url}
            onChange={(url) => setEditForm({ ...editForm, avatar_url: url })}
          />
          <div className="flex justify-end gap-3 pt-2">
            <Button variant="outline" onClick={() => setShowEditDialog(false)}>
              취소
            </Button>
            <Button onClick={handleEditEmployee}>수정</Button>
          </div>
        </div>
      </Dialog>
      {/* ─── 비밀번호 변경 다이얼로그 ────────────────────── */}
      <Dialog
        open={showPasswordDialog}
        onClose={() => setShowPasswordDialog(false)}
        title={`비밀번호 변경 — ${passwordTarget?.name}`}
      >
        <div className="space-y-4">
          <p className="text-sm text-gray-500">
            {passwordTarget?.name}님의 비밀번호를 변경합니다. 변경 후 해당 직원에게 새 비밀번호를 전달해주세요.
          </p>
          <Input
            id="reset-password"
            label="새 비밀번호"
            value={newPassword}
            onChange={(e) => setNewPassword(e.target.value)}
            placeholder="6자 이상"
          />
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={() => setNewPassword(generateTempPassword())}
              className="text-xs text-brand-600 hover:text-brand-700 underline"
            >
              임시 비밀번호 재생성
            </button>
          </div>
          <div className="flex justify-end gap-3 pt-2">
            <Button variant="outline" onClick={() => setShowPasswordDialog(false)}>
              취소
            </Button>
            <Button onClick={handleResetPassword} disabled={resettingPassword}>
              {resettingPassword ? '변경 중...' : '비밀번호 변경'}
            </Button>
          </div>
        </div>
      </Dialog>
    </div>
  )
}
