import { useCallback, useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'
import type { Department, Employee, EmployeeRole } from '@/types/database'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'
import { Select } from '@/components/ui/Select'
import { Badge } from '@/components/ui/Badge'
import { Dialog } from '@/components/ui/Dialog'
import { PageSpinner } from '@/components/ui/Spinner'
import { useToast } from '@/components/ui/Toast'
import { AvatarPicker, resolveAvatarSrc } from '@/components/ui/AvatarPicker'
import { ROLE_LABELS } from '@/lib/constants'
import { generateEmail, generateEmailPrefix, generateAlternativeEmails, DOMAIN } from '@/lib/email-generator'
import {
  Plus,
  Pencil,
  Building2,
  Users,
  UserPlus,
  UserX,
  UserCheck,
  Trash2,
} from 'lucide-react'

/** 자기평가 대상이 될 수 있는 역할 */
const SELF_EVAL_ELIGIBLE_ROLES: string[] = ['employee', 'leader']

const ROLE_OPTIONS: { value: string; label: string }[] = [
  { value: 'employee', label: '직원' },
  { value: 'leader', label: '리더' },
  { value: 'director', label: '이사' },
  { value: 'division_head', label: '본부장' },
  { value: 'ceo', label: '대표이사' },
  { value: 'admin', label: '관리자' },
]

export default function TabEmployees() {
  const { toast } = useToast()
  const [departments, setDepartments] = useState<Department[]>([])
  const [employees, setEmployees] = useState<(Employee & { department?: Department })[]>([])
  const [loading, setLoading] = useState(true)

  // 부서 다이얼로그
  const [showDeptDialog, setShowDeptDialog] = useState(false)
  const [editingDept, setEditingDept] = useState<Department | null>(null)
  const [deptName, setDeptName] = useState('')

  // 직원 추가 다이얼로그
  const [showInviteDialog, setShowInviteDialog] = useState(false)
  const [inviteForm, setInviteForm] = useState({
    email: '',
    name: '',
    department_id: '',
    role: 'employee' as EmployeeRole,
    password: '',
    birth_date: '',
    address: '',
    phone: '',
    avatar_url: '',
  })
  const [inviting, setInviting] = useState(false)
  const [emailSuggestions, setEmailSuggestions] = useState<string[]>([])
  const [emailAutoGenerated, setEmailAutoGenerated] = useState(false)

  // 직원 수정 다이얼로그
  const [showEditDialog, setShowEditDialog] = useState(false)
  const [editingEmployee, setEditingEmployee] = useState<Employee | null>(null)
  const [editForm, setEditForm] = useState({
    department_id: '',
    role: '',
    birth_date: '',
    address: '',
    phone: '',
    avatar_url: '',
  })

  // 필터
  const [filterDept, setFilterDept] = useState<string>('all')

  // 자기평가 토글 관련
  const [activePeriodId, setActivePeriodId] = useState<string | null>(null)
  const [evalTargets, setEvalTargets] = useState<Record<string, { id: string; status: string }>>({})
  const [togglingEval, setTogglingEval] = useState<Set<string>>(new Set())

  const fetchData = useCallback(async () => {
    const [deptRes, empRes, periodRes] = await Promise.all([
      supabase.from('departments').select('*').order('name'),
      supabase.from('employees').select('*, department:departments(*)').order('name'),
      supabase.from('evaluation_periods').select('*').eq('status', 'in_progress').limit(1).single(),
    ])
    setDepartments(deptRes.data ?? [])
    setEmployees(empRes.data ?? [])

    if (periodRes.data) {
      setActivePeriodId(periodRes.data.id)
      const { data: targets } = await supabase
        .from('evaluation_targets')
        .select('id, employee_id, status')
        .eq('period_id', periodRes.data.id)
      const targetMap: Record<string, { id: string; status: string }> = {}
      targets?.forEach((t: any) => {
        targetMap[t.employee_id] = { id: t.id, status: t.status }
      })
      setEvalTargets(targetMap)
    }

    setLoading(false)
  }, [])

  useEffect(() => {
    fetchData()
  }, [fetchData])

  // ─── 이름 변경 시 이메일 자동 생성 ─────────────────────────────
  async function handleNameChange(name: string) {
    setInviteForm((f) => ({ ...f, name }))

    const email = generateEmail(name)
    if (!email) {
      setEmailSuggestions([])
      if (emailAutoGenerated) setInviteForm((f) => ({ ...f, email: '' }))
      return
    }

    // 자동생성된 이메일이면 자동 갱신
    setInviteForm((f) => ({ ...f, name, email }))
    setEmailAutoGenerated(true)

    // 중복 체크
    const prefix = generateEmailPrefix(name)
    const { data: existing } = await supabase
      .from('employees')
      .select('email')
      .ilike('email', `${prefix}%@${DOMAIN}`)

    if (existing && existing.length > 0) {
      const alts = generateAlternativeEmails(name, existing.length)
      setEmailSuggestions(alts)
      // 기본 이메일이 이미 존재하면 첫 번째 대안으로 설정
      if (existing.some((e) => e.email === email)) {
        setInviteForm((f) => ({ ...f, email: alts[0] || email }))
      }
    } else {
      setEmailSuggestions([])
    }
  }

  function handleEmailManualChange(email: string) {
    setInviteForm((f) => ({ ...f, email }))
    setEmailAutoGenerated(false)
  }

  // ─── 부서 관리 ────────────────────────────────────────────────

  function openCreateDept() {
    setEditingDept(null)
    setDeptName('')
    setShowDeptDialog(true)
  }

  function openEditDept(dept: Department) {
    setEditingDept(dept)
    setDeptName(dept.name)
    setShowDeptDialog(true)
  }

  async function handleSaveDept() {
    if (!deptName.trim()) {
      toast('부서명을 입력해주세요', 'error')
      return
    }

    if (editingDept) {
      const { error } = await supabase
        .from('departments')
        .update({ name: deptName })
        .eq('id', editingDept.id)
      if (error) {
        toast('수정 실패: ' + error.message, 'error')
      } else {
        toast('부서명이 수정되었습니다')
        setShowDeptDialog(false)
        fetchData()
      }
    } else {
      const { error } = await supabase.from('departments').insert({ name: deptName })
      if (error) {
        toast('생성 실패: ' + error.message, 'error')
      } else {
        toast('부서가 생성되었습니다')
        setShowDeptDialog(false)
        fetchData()
      }
    }
  }

  async function handleDeleteDept(dept: Department) {
    const deptEmployees = employees.filter((e) => e.department_id === dept.id)
    if (deptEmployees.length > 0) {
      toast('직원이 있는 부서는 삭제할 수 없습니다', 'error')
      return
    }
    if (!confirm(`"${dept.name}" 부서를 삭제하시겠습니까?`)) return

    const { error } = await supabase.from('departments').delete().eq('id', dept.id)
    if (error) {
      toast('삭제 실패: ' + error.message, 'error')
    } else {
      toast('부서가 삭제되었습니다')
      fetchData()
    }
  }

  // ─── 직원 초대 ────────────────────────────────────────────────

  function openInvite() {
    setInviteForm({
      email: '',
      name: '',
      department_id: departments[0]?.id ?? '',
      role: 'employee',
      password: generateTempPassword(),
      birth_date: '',
      address: '',
      phone: '',
      avatar_url: '',
    })
    setEmailSuggestions([])
    setEmailAutoGenerated(false)
    setShowInviteDialog(true)
  }

  function generateTempPassword() {
    return 'Temp' + Math.random().toString(36).slice(2, 8) + '!'
  }

  async function handleInvite() {
    if (!inviteForm.email || !inviteForm.name) {
      toast('이메일과 이름을 입력해주세요', 'error')
      return
    }
    setInviting(true)

    // Step 1: RPC로 auth.users + employees 기본 레코드 생성
    const { data, error } = await supabase.rpc('create_employee_with_auth', {
      p_email: inviteForm.email,
      p_password: inviteForm.password,
      p_name: inviteForm.name,
      p_role: inviteForm.role,
      p_department_id: inviteForm.department_id || null,
    })

    if (error) {
      toast('직원 등록 실패: ' + error.message, 'error')
    } else {
      // Step 2: 추가 필드 업데이트 (birth_date, address, phone, avatar_url)
      const employeeId = data as string
      const extraFields: Record<string, string | null> = {}
      if (inviteForm.birth_date) extraFields.birth_date = inviteForm.birth_date
      if (inviteForm.address) extraFields.address = inviteForm.address
      if (inviteForm.phone) extraFields.phone = inviteForm.phone
      if (inviteForm.avatar_url) extraFields.avatar_url = inviteForm.avatar_url

      if (Object.keys(extraFields).length > 0 && employeeId) {
        await supabase.from('employees').update(extraFields).eq('id', employeeId)
      }

      toast(`${inviteForm.name}님이 등록되었습니다. 임시 비밀번호: ${inviteForm.password}`, 'info')
      setShowInviteDialog(false)
      fetchData()
    }
    setInviting(false)
  }

  // ─── 직원 수정 ────────────────────────────────────────────────

  function openEditEmployee(emp: Employee) {
    setEditingEmployee(emp)
    setEditForm({
      department_id: emp.department_id ?? '',
      role: emp.role,
      birth_date: emp.birth_date ?? '',
      address: emp.address ?? '',
      phone: emp.phone ?? '',
      avatar_url: emp.avatar_url ?? '',
    })
    setShowEditDialog(true)
  }

  async function handleEditEmployee() {
    if (!editingEmployee) return

    const { error } = await supabase
      .from('employees')
      .update({
        department_id: editForm.department_id || null,
        role: editForm.role,
        birth_date: editForm.birth_date || null,
        address: editForm.address || null,
        phone: editForm.phone || null,
        avatar_url: editForm.avatar_url || null,
      })
      .eq('id', editingEmployee.id)

    if (error) {
      toast('수정 실패: ' + error.message, 'error')
    } else {
      toast('직원 정보가 수정되었습니다')
      setShowEditDialog(false)
      fetchData()
    }
  }

  async function handleToggleActive(emp: Employee) {
    const action = emp.is_active ? '비활성화' : '활성화'
    if (!confirm(`${emp.name}님을 ${action}하시겠습니까?`)) return

    const { error } = await supabase
      .from('employees')
      .update({ is_active: !emp.is_active })
      .eq('id', emp.id)

    if (error) {
      toast('변경 실패: ' + error.message, 'error')
    } else {
      toast(`${emp.name}님이 ${action}되었습니다`)
      fetchData()
    }
  }

  async function handleDeleteEmployee(emp: Employee) {
    if (!confirm(`${emp.name}님을 완전히 삭제하시겠습니까?\n이 작업은 되돌릴 수 없으며, 관련 평가 데이터도 모두 삭제됩니다.`)) return

    const { error } = await supabase.rpc('delete_employee', {
      p_employee_id: emp.id,
    })

    if (error) {
      toast('삭제 실패: ' + error.message, 'error')
    } else {
      toast(`${emp.name}님이 삭제되었습니다`)
      fetchData()
    }
  }

  async function handleToggleSelfEval(emp: Employee) {
    if (!activePeriodId) {
      toast('진행 중인 평가 기간이 없습니다', 'error')
      return
    }
    if (!SELF_EVAL_ELIGIBLE_ROLES.includes(emp.role)) {
      toast('해당 역할은 자기평가 대상이 아닙니다', 'error')
      return
    }

    setTogglingEval((prev) => new Set(prev).add(emp.id))

    const existing = evalTargets[emp.id]
    if (existing) {
      if (existing.status !== 'pending') {
        toast('이미 진행된 평가는 비활성화할 수 없습니다', 'error')
        setTogglingEval((prev) => { const s = new Set(prev); s.delete(emp.id); return s })
        return
      }
      await supabase.from('self_evaluations').delete().eq('target_id', existing.id)
      const { error } = await supabase.from('evaluation_targets').delete().eq('id', existing.id)
      if (error) {
        toast('자기평가 비활성화 실패: ' + error.message, 'error')
      } else {
        toast(`${emp.name}님의 자기평가가 비활성화되었습니다`)
        setEvalTargets((prev) => { const next = { ...prev }; delete next[emp.id]; return next })
      }
    } else {
      const { data: newTarget, error } = await supabase
        .from('evaluation_targets')
        .insert({ period_id: activePeriodId, employee_id: emp.id, status: 'pending' })
        .select('id')
        .single()

      if (error) {
        toast('자기평가 활성화 실패: ' + error.message, 'error')
      } else if (newTarget) {
        const { data: activeItems } = await supabase
          .from('evaluation_items')
          .select('id')
          .eq('is_active', true)
        if (activeItems && activeItems.length > 0) {
          await supabase.from('self_evaluations').insert(
            activeItems.map((item: any) => ({ target_id: newTarget.id, item_id: item.id }))
          )
        }
        toast(`${emp.name}님의 자기평가가 활성화되었습니다`)
        setEvalTargets((prev) => ({ ...prev, [emp.id]: { id: newTarget.id, status: 'pending' } }))
      }
    }

    setTogglingEval((prev) => { const s = new Set(prev); s.delete(emp.id); return s })
  }

  if (loading) return <PageSpinner />

  const filteredEmployees =
    filterDept === 'all'
      ? employees
      : filterDept === 'none'
      ? employees.filter((e) => !e.department_id)
      : employees.filter((e) => e.department_id === filterDept)

  return (
    <div className="space-y-6">
      <p className="text-sm text-gray-500">부서 및 직원 정보를 관리합니다.</p>

      {/* ─── 부서 관리 ──────────────────────────────────────── */}
      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <div className="flex items-center gap-2">
            <Building2 className="h-5 w-5 text-gray-400" />
            <CardTitle>부서 관리</CardTitle>
          </div>
          <Button size="sm" onClick={openCreateDept}>
            <Plus className="h-3 w-3 mr-1" />
            부서 추가
          </Button>
        </CardHeader>
        <CardContent>
          {departments.length === 0 ? (
            <p className="text-sm text-gray-400 text-center py-4">등록된 부서가 없습니다</p>
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
              {departments.map((dept) => {
                const count = employees.filter((e) => e.department_id === dept.id).length
                return (
                  <div
                    key={dept.id}
                    className="flex items-center justify-between rounded-lg border border-gray-200 px-4 py-3"
                  >
                    <div>
                      <p className="text-sm font-medium text-gray-900">{dept.name}</p>
                      <p className="text-xs text-gray-500">{count}명</p>
                    </div>
                    <div className="flex gap-1">
                      <button
                        onClick={() => openEditDept(dept)}
                        className="rounded p-1 text-gray-400 hover:bg-gray-100 hover:text-gray-600"
                      >
                        <Pencil className="h-3.5 w-3.5" />
                      </button>
                      <button
                        onClick={() => handleDeleteDept(dept)}
                        className="rounded p-1 text-gray-400 hover:bg-red-50 hover:text-red-600"
                      >
                        <Trash2 className="h-3.5 w-3.5" />
                      </button>
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </CardContent>
      </Card>

      {/* ─── 직원 관리 ──────────────────────────────────────── */}
      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <div className="flex items-center gap-2">
            <Users className="h-5 w-5 text-gray-400" />
            <CardTitle>직원 관리</CardTitle>
            <Badge variant="default">{employees.length}명</Badge>
          </div>
          <div className="flex items-center gap-3">
            <Select
              options={[
                { value: 'all', label: '전체' },
                ...departments.map((d) => ({ value: d.id, label: d.name })),
                { value: 'none', label: '부서 미지정' },
              ]}
              value={filterDept}
              onChange={(e) => setFilterDept(e.target.value)}
              className="w-40"
            />
            <Button size="sm" onClick={openInvite}>
              <UserPlus className="h-3 w-3 mr-1" />
              직원 추가
            </Button>
          </div>
        </CardHeader>
        <CardContent className="p-0">
          {filteredEmployees.length === 0 ? (
            <div className="flex h-20 items-center justify-center text-sm text-gray-400">
              직원이 없습니다
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-gray-100 bg-gray-50">
                    <th className="px-6 py-3 text-left font-medium text-gray-500">이름</th>
                    <th className="px-6 py-3 text-left font-medium text-gray-500">이메일</th>
                    <th className="px-6 py-3 text-left font-medium text-gray-500">부서</th>
                    <th className="px-6 py-3 text-left font-medium text-gray-500">역할</th>
                    <th className="px-6 py-3 text-left font-medium text-gray-500">상태</th>
                    {activePeriodId && (
                      <th className="px-6 py-3 text-center font-medium text-gray-500">자기평가</th>
                    )}
                    <th className="px-6 py-3 text-left font-medium text-gray-500">작업</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredEmployees.map((emp) => {
                    const avatarSrc = resolveAvatarSrc(emp.avatar_url)
                    return (
                      <tr
                        key={emp.id}
                        className={`border-b border-gray-50 ${
                          emp.is_active ? 'hover:bg-gray-50' : 'bg-gray-50 opacity-60'
                        }`}
                      >
                        <td className="px-6 py-3 font-medium text-gray-900">
                          <div className="flex items-center gap-2">
                            {avatarSrc ? (
                              <img src={avatarSrc} alt="" className="h-7 w-7 rounded-full" />
                            ) : (
                              <div className="h-7 w-7 rounded-full bg-gray-200 flex items-center justify-center text-xs text-gray-500">
                                {emp.name.charAt(0)}
                              </div>
                            )}
                            {emp.name}
                          </div>
                        </td>
                        <td className="px-6 py-3 text-gray-600">{emp.email}</td>
                        <td className="px-6 py-3 text-gray-600">
                          {(emp as any).department?.name ?? '-'}
                        </td>
                        <td className="px-6 py-3">
                          <Badge variant="primary">
                            {ROLE_LABELS[emp.role as EmployeeRole] ?? emp.role}
                          </Badge>
                        </td>
                        <td className="px-6 py-3">
                          <Badge variant={emp.is_active ? 'success' : 'danger'}>
                            {emp.is_active ? '활성' : '비활성'}
                          </Badge>
                        </td>
                        {activePeriodId && (
                          <td className="px-6 py-3 text-center">
                            {SELF_EVAL_ELIGIBLE_ROLES.includes(emp.role) ? (
                              <button
                                onClick={() => handleToggleSelfEval(emp)}
                                disabled={togglingEval.has(emp.id) || (evalTargets[emp.id]?.status != null && evalTargets[emp.id]?.status !== 'pending')}
                                className="relative inline-flex h-6 w-11 items-center rounded-full transition-colors focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2 disabled:opacity-50"
                                style={{
                                  backgroundColor: evalTargets[emp.id] ? '#6d28d9' : '#d1d5db',
                                }}
                                title={
                                  evalTargets[emp.id]
                                    ? evalTargets[emp.id].status !== 'pending'
                                      ? `진행 중 (${evalTargets[emp.id].status})`
                                      : '자기평가 활성 — 클릭하여 비활성화'
                                    : '자기평가 비활성 — 클릭하여 활성화'
                                }
                              >
                                <span
                                  className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                                    evalTargets[emp.id] ? 'translate-x-6' : 'translate-x-1'
                                  }`}
                                />
                              </button>
                            ) : (
                              <span className="text-xs text-gray-400">—</span>
                            )}
                          </td>
                        )}
                        <td className="px-6 py-3">
                          <div className="flex gap-1">
                            <button
                              onClick={() => openEditEmployee(emp)}
                              className="rounded p-1 text-gray-400 hover:bg-gray-100 hover:text-gray-600"
                              title="수정"
                            >
                              <Pencil className="h-4 w-4" />
                            </button>
                            <button
                              onClick={() => handleToggleActive(emp)}
                              className="rounded p-1 text-gray-400 hover:bg-gray-100 hover:text-gray-600"
                              title={emp.is_active ? '비활성화' : '활성화'}
                            >
                              {emp.is_active ? (
                                <UserX className="h-4 w-4" />
                              ) : (
                                <UserCheck className="h-4 w-4" />
                              )}
                            </button>
                            <button
                              onClick={() => handleDeleteEmployee(emp)}
                              className="rounded p-1 text-gray-400 hover:bg-red-50 hover:text-red-600"
                              title="삭제"
                            >
                              <Trash2 className="h-4 w-4" />
                            </button>
                          </div>
                        </td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>

      {/* ─── 부서 추가/수정 다이얼로그 ─────────────────────── */}
      <Dialog
        open={showDeptDialog}
        onClose={() => setShowDeptDialog(false)}
        title={editingDept ? '부서 수정' : '부서 추가'}
      >
        <div className="space-y-4">
          <Input
            id="dept-name"
            label="부서명"
            value={deptName}
            onChange={(e) => setDeptName(e.target.value)}
            placeholder="예: 브랜드사업본부"
          />
          <div className="flex justify-end gap-3 pt-2">
            <Button variant="outline" onClick={() => setShowDeptDialog(false)}>
              취소
            </Button>
            <Button onClick={handleSaveDept}>
              {editingDept ? '수정' : '추가'}
            </Button>
          </div>
        </div>
      </Dialog>

      {/* ─── 직원 추가 다이얼로그 ──────────────────────────── */}
      <Dialog
        open={showInviteDialog}
        onClose={() => setShowInviteDialog(false)}
        title="직원 추가"
        className="max-w-xl"
      >
        <div className="space-y-4 max-h-[70vh] overflow-y-auto pr-1">
          <Input
            id="invite-name"
            label="이름"
            value={inviteForm.name}
            onChange={(e) => handleNameChange(e.target.value)}
            placeholder="홍길동"
          />
          <div>
            <Input
              id="invite-email"
              label="이메일"
              type="email"
              value={inviteForm.email}
              onChange={(e) => handleEmailManualChange(e.target.value)}
              placeholder="user@interohrigin.com"
            />
            {emailSuggestions.length > 0 && (
              <div className="mt-1.5 flex flex-wrap gap-1.5">
                <span className="text-xs text-gray-500">추천:</span>
                {emailSuggestions.map((alt) => (
                  <button
                    key={alt}
                    type="button"
                    onClick={() => {
                      setInviteForm((f) => ({ ...f, email: alt }))
                      setEmailAutoGenerated(true)
                    }}
                    className="rounded-full bg-brand-50 px-2 py-0.5 text-xs text-brand-700 hover:bg-brand-100 transition-colors"
                  >
                    {alt}
                  </button>
                ))}
              </div>
            )}
          </div>
          <div className="grid grid-cols-2 gap-4">
            <Select
              id="invite-dept"
              label="부서"
              options={[
                { value: '', label: '부서 미지정' },
                ...departments.map((d) => ({ value: d.id, label: d.name })),
              ]}
              value={inviteForm.department_id}
              onChange={(e) => setInviteForm({ ...inviteForm, department_id: e.target.value })}
            />
            <Select
              id="invite-role"
              label="역할"
              options={ROLE_OPTIONS}
              value={inviteForm.role}
              onChange={(e) =>
                setInviteForm({ ...inviteForm, role: e.target.value as EmployeeRole })
              }
            />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <Input
              id="invite-birth"
              label="생년월일"
              type="date"
              value={inviteForm.birth_date}
              onChange={(e) => setInviteForm({ ...inviteForm, birth_date: e.target.value })}
            />
            <Input
              id="invite-phone"
              label="연락처"
              type="tel"
              value={inviteForm.phone}
              onChange={(e) => setInviteForm({ ...inviteForm, phone: e.target.value })}
              placeholder="010-0000-0000"
            />
          </div>
          <Input
            id="invite-address"
            label="주소"
            value={inviteForm.address}
            onChange={(e) => setInviteForm({ ...inviteForm, address: e.target.value })}
            placeholder="서울특별시 강남구..."
          />
          <AvatarPicker
            value={inviteForm.avatar_url}
            onChange={(url) => setInviteForm({ ...inviteForm, avatar_url: url })}
          />
          <div>
            <Input
              id="invite-password"
              label="임시 비밀번호"
              value={inviteForm.password}
              onChange={(e) => setInviteForm({ ...inviteForm, password: e.target.value })}
            />
            <p className="mt-1 text-xs text-gray-500">
              직원에게 이 임시 비밀번호를 전달해주세요. 최초 로그인 후 변경 권장.
            </p>
          </div>
          <div className="flex justify-end gap-3 pt-2">
            <Button variant="outline" onClick={() => setShowInviteDialog(false)}>
              취소
            </Button>
            <Button onClick={handleInvite} disabled={inviting}>
              {inviting ? '등록 중...' : '등록'}
            </Button>
          </div>
        </div>
      </Dialog>

      {/* ─── 직원 수정 다이얼로그 ──────────────────────────── */}
      <Dialog
        open={showEditDialog}
        onClose={() => setShowEditDialog(false)}
        title={`직원 수정 — ${editingEmployee?.name}`}
        className="max-w-xl"
      >
        <div className="space-y-4 max-h-[70vh] overflow-y-auto pr-1">
          <div className="grid grid-cols-2 gap-4">
            <Select
              id="edit-dept"
              label="부서"
              options={[
                { value: '', label: '부서 미지정' },
                ...departments.map((d) => ({ value: d.id, label: d.name })),
              ]}
              value={editForm.department_id}
              onChange={(e) => setEditForm({ ...editForm, department_id: e.target.value })}
            />
            <Select
              id="edit-role"
              label="역할"
              options={ROLE_OPTIONS}
              value={editForm.role}
              onChange={(e) => setEditForm({ ...editForm, role: e.target.value })}
            />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <Input
              id="edit-birth"
              label="생년월일"
              type="date"
              value={editForm.birth_date}
              onChange={(e) => setEditForm({ ...editForm, birth_date: e.target.value })}
            />
            <Input
              id="edit-phone"
              label="연락처"
              type="tel"
              value={editForm.phone}
              onChange={(e) => setEditForm({ ...editForm, phone: e.target.value })}
              placeholder="010-0000-0000"
            />
          </div>
          <Input
            id="edit-address"
            label="주소"
            value={editForm.address}
            onChange={(e) => setEditForm({ ...editForm, address: e.target.value })}
            placeholder="서울특별시 강남구..."
          />
          <AvatarPicker
            value={editForm.avatar_url}
            onChange={(url) => setEditForm({ ...editForm, avatar_url: url })}
          />
          <div className="flex justify-end gap-3 pt-2">
            <Button variant="outline" onClick={() => setShowEditDialog(false)}>
              취소
            </Button>
            <Button onClick={handleEditEmployee}>수정</Button>
          </div>
        </div>
      </Dialog>
    </div>
  )
}
